### ISSUE TITLE
Build the OrfTrimmer module

### ISSUE THREAD

**Issue by DavidEHufnagel** [CDCgov/clean-genes#2]
This is the next major step in development

**Comment by sammysheep** [comment]
ORF trimmer?

**Comment by DavidEHufnagel** [comment]
Yes, so this is the first "important thing" that clean-genes will do: trim all the sequences in an alignment to a common start and stop codon. The assumption is that all the sequences involved follow the assumptions of what should be aligned for the purpose of phylogenetics: They are similar due to common ancestry and can be understood properly under a single reading frame.

**Comment by DavidEHufnagel** [comment]
It's not yet perfect, or even well-tested, but it's built.

**Comment by sammysheep** [comment]
When I do prep for phylogenetic, particularly for HA, I do not always want things trimmed to start / stop because of ragged ends.

The minimum support for the column is what matters more to me. In that case, you are essentially looking for longest open reading frame.

**Comment by DavidEHufnagel** [comment]
Interesting, let's dig deeper during tomorrow morning's meeting!

**Comment by DavidEHufnagel** [comment]
I will make the whole software modular such that you can pick and choose what you want done. The software will choose for you what order these modules occur in though unless you choose to run them one-at-a-time.
